name: cl_store_local
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
