name: cl_dart_extensions
description: A collection of extensions defined for standard data types.
version: 0.1.0

environment:
  sdk: ^3.6.0

#dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  intl: ^0.20.2
  meta: ^1.16.0
  path: ^1.9.1
