name: cl_store
description: A starting point for Dart libraries or applications.
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  cl_dart_extensions:
    path: ../cl_dart_extensions
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
